import type { CardDefinition } from '../types/card.js';

export const CARD_DEFINITIONS: CardDefinition[] = [
  {
    id: 'ember-knight',
    name: 'Ember Knight',
    description: 'A fiery warrior forged in volcanic heat.',
    rarity: 'common',
    element: 'fire',
    attack: 3,
    defense: 2,
    cost: 2,
    ability: null,
    imageUrl: '/cards/ember-knight.svg',
  },
  {
    id: 'tide-sage',
    name: 'Tide Sage',
    description: 'Channels ocean currents to shield allies.',
    rarity: 'common',
    element: 'water',
    attack: 2,
    defense: 3,
    cost: 2,
    ability: null,
    imageUrl: '/cards/tide-sage.svg',
  },
  {
    id: 'stone-guardian',
    name: 'Stone Guardian',
    description: 'An immovable defender of ancient ruins.',
    rarity: 'common',
    element: 'earth',
    attack: 1,
    defense: 5,
    cost: 3,
    ability: null,
    imageUrl: '/cards/stone-guardian.svg',
  },
  {
    id: 'wind-striker',
    name: 'Wind Striker',
    description: 'Strikes before the eye can follow.',
    rarity: 'common',
    element: 'air',
    attack: 4,
    defense: 1,
    cost: 2,
    ability: null,
    imageUrl: '/cards/wind-striker.svg',
  },
  {
    id: 'flame-drake',
    name: 'Flame Drake',
    description: 'A young dragon wreathed in flames.',
    rarity: 'uncommon',
    element: 'fire',
    attack: 5,
    defense: 3,
    cost: 4,
    ability: 'Deals 1 damage to opponent on play.',
    imageUrl: '/cards/flame-drake.svg',
  },
  {
    id: 'frost-warden',
    name: 'Frost Warden',
    description: 'Freezes enemies with icy resolve.',
    rarity: 'uncommon',
    element: 'water',
    attack: 3,
    defense: 4,
    cost: 4,
    ability: 'Reduces opponent attack by 1 next turn.',
    imageUrl: '/cards/frost-warden.svg',
  },
  {
    id: 'earth-titan',
    name: 'Earth Titan',
    description: 'A colossal being of living stone.',
    rarity: 'rare',
    element: 'earth',
    attack: 6,
    defense: 6,
    cost: 6,
    ability: 'Gains +1 defense when damaged.',
    imageUrl: '/cards/earth-titan.svg',
  },
  {
    id: 'storm-harbinger',
    name: 'Storm Harbinger',
    description: 'Commands lightning across the battlefield.',
    rarity: 'rare',
    element: 'air',
    attack: 7,
    defense: 2,
    cost: 5,
    ability: 'Attacks bypass defense once per match.',
    imageUrl: '/cards/storm-harbinger.svg',
  },
  {
    id: 'void-sentinel',
    name: 'Void Sentinel',
    description: 'A neutral guardian from the space between elements.',
    rarity: 'epic',
    element: 'neutral',
    attack: 5,
    defense: 5,
    cost: 5,
    ability: 'Adapts element to counter opponent.',
    imageUrl: '/cards/void-sentinel.svg',
  },
  {
    id: 'primordial-phoenix',
    name: 'Primordial Phoenix',
    description: 'Legendary firebird reborn from ashes.',
    rarity: 'legendary',
    element: 'fire',
    attack: 8,
    defense: 4,
    cost: 7,
    ability: 'Returns to hand once when destroyed.',
    imageUrl: '/cards/primordial-phoenix.svg',
  },
  {
    id: 'abyssal-leviathan',
    name: 'Abyssal Leviathan',
    description: 'Ancient sea monster of unfathomable depth.',
    rarity: 'legendary',
    element: 'water',
    attack: 7,
    defense: 7,
    cost: 8,
    ability: 'Heals 3 health on play.',
    imageUrl: '/cards/abyssal-leviathan.svg',
  },
  {
    id: 'training-dummy',
    name: 'Training Dummy',
    description: 'Basic practice unit for new recruits.',
    rarity: 'common',
    element: 'neutral',
    attack: 1,
    defense: 1,
    cost: 1,
    ability: null,
    imageUrl: '/cards/training-dummy.svg',
  },
];

export const CARD_MAP = new Map(CARD_DEFINITIONS.map((c) => [c.id, c]));

export function getCard(id: string): CardDefinition | undefined {
  return CARD_MAP.get(id);
}

export function getStarterDeck(): { cardId: string; quantity: number }[] {
  return [
    { cardId: 'training-dummy', quantity: 3 },
    { cardId: 'ember-knight', quantity: 3 },
    { cardId: 'tide-sage', quantity: 3 },
    { cardId: 'stone-guardian', quantity: 3 },
    { cardId: 'wind-striker', quantity: 3 },
    { cardId: 'flame-drake', quantity: 3 },
    { cardId: 'frost-warden', quantity: 3 },
    { cardId: 'earth-titan', quantity: 2 },
    { cardId: 'storm-harbinger', quantity: 2 },
    { cardId: 'void-sentinel', quantity: 2 },
    { cardId: 'primordial-phoenix', quantity: 1 },
    { cardId: 'abyssal-leviathan', quantity: 2 },
  ];
}
